### ISSUE TITLE
Pushing towards 1.1 release

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/react-handsontable#81]
1.0 release was a great milestone 🦄  👍 
But there are still few things we need to address in Handsontable for React.

- [x] Set `react-handsontable` npm package as deprecated (check `angular-handsontable` for Readme.md and deprecation message templates)
- [x] Improve [Redux example](https://docs.handsontable.com/4.0.0/frameworks-wrapper-for-react-examples-redux.html) with #23
- [x] Add Issue template #87 
- [x] Add Pull Request template #87
- [x] Fix small Readme issues: #77 and #78 
- [x] It's good idea to use `ref` inside component: #19  
- [x] But `id` should stay anyway #76  
- [x] Add Typescript definition file or "rewrite" to Typescript #14 
- [x] Add sourcemaps for `min.(js|css)` files (and `.js` file if we go the Typescript path) #94
- [x] Wrong browser component global. #89
